# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        arguments:
            - '@fos_user.user_manager'
            - '@router'
            - '@security.user_password_encoder.generic'
            - '@security.csrf.token_manager'
