# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        arguments:
            - '@fos_user.user_manager'
            - '@router'
            - '@security.user_password_encoder.generic'
            - '@security.csrf.token_manager'

    app.authorization_manager:
        class: AppBundle\Service\AuthorizationManager
        arguments:
            - '@doctrine.orm.entity_manager'

    app.oauth_event_listener:
        class: AppBundle\EventListener\OAuthEventListener
        arguments:
            - '@app.authorization_manager'
            - '@fos_user.user_manager'
        tags:
            - name: kernel.event_listener
              event: fos_oauth_server.pre_authorization_process
              method: onPreAuthorizationProcess
            - name: kernel.event_listener
              event: fos_oauth_server.post_authorization_process
              method: onPostAuthorizationProcess
