AppBundle\Entity\AccessToken:
    exclusion_policy: ALL
    properties:
        id:
            expose: false
        client:
            expose: false
        token:
            expose: true
        expiresAt:
            expose: true
        user:
            expose: true
